### ISSUE TITLE
Use Requirement Specifiers for pip

### ISSUE THREAD

**Issue by imsofi** [zommiommy/cache_decorator#2]
Allow the installation of cache_decorator trough pip without the need for unneeded extra packages such as `pandas` and `numpy`.

To avoid extra packages from being unnecessarily installed, cache_decorator could normally ship only with the basic functionality (ex `.json`). Where the if the user wants it, extra packages such as pandas and numpy would be added into the requirement specifiers.

Example of usage following [PEP508](https://www.python.org/dev/peps/pep-0508/):
```bash
$ pip install cache_decorator
$ pip install cache_decorator[pandas]
$ pip install cache_decorator[pandas, numpy]
```

**Comment by zommiommy** [comment]
Hi! Thanks for the issue, I'm on it!

**Comment by zommiommy** [comment]
I have updated the extras and now it should works as you proposed.
Take a look if the changes I've done are reasonable.

In the commit, I said that this fixed only _part_ of the problem because the package I use to compute the hash of the arguments [dict_hash](https://github.com/LucaCappelletti94/dict_hash) also requires numpy and pandas.

If I have some more time later I'll do a pull request to add this feature also to that package.

Once it's implemented, how would the setup work? How Can I "forward" the extra choice to the dependency package?

**Comment by imsofi** [comment]
> How Can I "forward" the extra choice to the dependency package?

Im not entirely sure what you mean by that. I sadly have only limited experience dealing with pip and setuptools. I wanted to try out the `cache_decorator` package and found it to install an extra 10 packages for functionality i wouldn't be using.

**Comment by zommiommy** [comment]
Done, I've updated it and now also dict_hash supports this feature. 
I've just pushed on pypi the new 1.4.0 version try it out. I hope this fixes the problem.
